// Generic unknown-key rejection and value-KIND checks, derived from the
// reference's own types.
//
// The reference's save door (create / update / `POST /flows/validate` / the
// Studio assistant) decodes a flow with yaml.v3 `KnownFields(true)`
// (`NewStrictFlowParser`, parser.go). That refuses, at EVERY depth, a key that
// the containing Go struct does not declare — a step-level `output:`, a typo
// such as `excutor:`, an unknown key inside `next:`, `error_strategy:`, a mock
// scenario step, a query parameter definition, an orchestrator trigger. It also
// fails to decode a value of the wrong KIND: `next: end` (a scalar where a
// mapping is required), a mapping where a string is required, a mapping where a
// list is required. Both are "would not save", so both are errors here.
//
// The key sets are NOT hand-listed. `KNOWN_KEYS` is generated by reflection over
// the reference's `Flow` type with yaml.v3's own field rules, and was checked
// against the reference's strict parser for every type and every key (PARITY.md).
//
// What stays open, because the reference leaves it open: a Go `map` has
// author-chosen keys (`steps`, `query` definitions, `mock_scenarios`,
// `executor_config`), a Go interface (`any`) is never inspected (a step's
// `query:`, `data:`, a mock's `content:`), and a pre/post-processing entry has
// its own unmarshaller (divergence #11 keeps its shape out of scope).
//
// Scalars are judged only for KIND (not mapping, not list). Whether `5` fits an
// int field or `abc` a bool is left to the rules that already own those fields
// (divergence #8).

import type { Flow } from '../types.js';
import { KNOWN_KEYS } from '../spec/index.js';
import { Issues, isRecord } from './util.js';

const CODE_UNKNOWN_YAML_KEY = 'unknown_yaml_key';
const CODE_INVALID_TYPE = 'invalid_type';

const SHAPE_SCALAR = 'scalar';
const SHAPE_ANY = 'any';
const MAP_PREFIX = 'map<';
const LIST_PREFIX = 'list<';
const SHAPE_SUFFIX = '>';

/**
 * Keys the reference DELETED from the grammar (`retiredGrammarKeys`, parser.go).
 * Its refusal names them wherever they appear, because the advice table matches
 * the key NAME in the decoder's error, not the type. The specific locations with
 * full advice are reported by retiredKeys.ts; this only keeps the generic
 * message from calling a once-valid key a typo.
 */
const RETIRED_KEYS: ReadonlySet<string> = new Set([
  'budget',
  'budget_exceeded_policy',
  'budget_max_per_child',
  'binary_results',
  'conversations',
  'max_retries',
  'message_templates',
  'unique_items',
]);

type Shape =
  | { kind: 'scalar' }
  | { kind: 'any' }
  | { kind: 'struct'; name: string }
  | { kind: 'map'; elem: Shape }
  | { kind: 'list'; elem: Shape };

const shapeCache = new Map<string, Shape>();

function parseShape(text: string): Shape {
  const cached = shapeCache.get(text);
  if (cached) return cached;
  let shape: Shape;
  if (text === SHAPE_SCALAR) shape = { kind: 'scalar' };
  else if (text === SHAPE_ANY) shape = { kind: 'any' };
  else if (text.startsWith(MAP_PREFIX) && text.endsWith(SHAPE_SUFFIX)) {
    shape = { kind: 'map', elem: parseShape(text.slice(MAP_PREFIX.length, -1)) };
  } else if (text.startsWith(LIST_PREFIX) && text.endsWith(SHAPE_SUFFIX)) {
    shape = { kind: 'list', elem: parseShape(text.slice(LIST_PREFIX.length, -1)) };
  } else if (Object.prototype.hasOwnProperty.call(KNOWN_KEYS.types, text)) {
    shape = { kind: 'struct', name: text };
  } else {
    // A spec defect, not a document defect: fail open rather than accuse every
    // flow. The spec test asserts every shape resolves, so this is unreachable
    // from a shipped build.
    shape = { kind: 'any' };
  }
  shapeCache.set(text, shape);
  return shape;
}

function child(path: string, key: string): string {
  return path === '' ? key : `${path}.${key}`;
}

/** The step id a finding under `steps.<id>` belongs to, for the summary count. */
function stepIdOf(path: string): string | undefined {
  if (!path.startsWith('steps.')) return undefined;
  const rest = path.slice('steps.'.length);
  const end = rest.search(/[.[]/);
  return end === -1 ? rest : rest.slice(0, end);
}

function kindName(value: unknown): string {
  if (Array.isArray(value)) return 'a list';
  if (isRecord(value)) return 'a mapping';
  return 'a scalar';
}

export function validateUnknownKeys(flow: Flow, issues: Issues): void {
  // Locations another rule already reported (with more specific advice) are not
  // reported twice: the retired keys and a condition's `goto_step`.
  const reported = new Set(
    issues.errors
      .filter((e) => e.code === CODE_UNKNOWN_YAML_KEY || e.code === CODE_INVALID_TYPE)
      .map((e) => `${e.code}\u0000${e.field}`),
  );

  const report = (code: string, field: string, message: string, suggestion?: string): void => {
    const id = `${code}\u0000${field}`;
    if (reported.has(id)) return;
    reported.add(id);
    const stepId = stepIdOf(field);
    issues.error({
      field,
      message,
      code,
      ...(stepId !== undefined ? { stepId } : {}),
      ...(suggestion !== undefined ? { suggestion } : {}),
    });
  };

  const walk = (value: unknown, shape: Shape, path: string): void => {
    // A YAML null decodes to the zero value of any Go type.
    if (value === null || value === undefined) return;

    switch (shape.kind) {
      case 'any':
        return;
      case 'scalar':
        if (isRecord(value) || Array.isArray(value)) {
          report(
            CODE_INVALID_TYPE,
            path,
            `'${path}' must be a single value, not ${kindName(value)}`,
          );
        }
        return;
      case 'list':
        if (!Array.isArray(value)) {
          report(CODE_INVALID_TYPE, path, `'${path}' must be a list, not ${kindName(value)}`);
          return;
        }
        value.forEach((item: unknown, i: number) => walk(item, shape.elem, `${path}[${i}]`));
        return;
      case 'map':
        if (!isRecord(value)) {
          report(CODE_INVALID_TYPE, path, `'${path}' must be a mapping, not ${kindName(value)}`);
          return;
        }
        for (const [key, item] of Object.entries(value)) walk(item, shape.elem, child(path, key));
        return;
      case 'struct': {
        if (!isRecord(value)) {
          report(
            CODE_INVALID_TYPE,
            path,
            `'${path === '' ? 'the flow' : path}' must be a mapping, not ${kindName(value)}`,
          );
          return;
        }
        const keys = KNOWN_KEYS.types[shape.name] ?? {};
        for (const [key, item] of Object.entries(value)) {
          const field = child(path, key);
          const declared = keys[key];
          if (declared === undefined) {
            const retired = RETIRED_KEYS.has(key)
              ? ' It was removed from the grammar and AIgentFlow refuses to save a flow that still declares it.'
              : '';
            report(
              CODE_UNKNOWN_YAML_KEY,
              field,
              `Unknown key '${key}'${path === '' ? ' at the top level' : ` in '${path}'`}.` +
                ` AIgentFlow refuses to save a flow with a key its grammar does not declare, because the key would be silently dropped.${retired}`,
              `Known keys here: ${Object.keys(keys).sort().join(', ')}`,
            );
            continue;
          }
          walk(item, parseShape(declared), field);
        }
        return;
      }
    }
  };

  walk(flow, { kind: 'struct', name: KNOWN_KEYS.root }, '');
}

/** Every shape string in the spec, for the spec self-test. */
export function unresolvedKnownKeyShapes(): string[] {
  const bad: string[] = [];
  const check = (text: string): boolean => {
    if (text === SHAPE_SCALAR || text === SHAPE_ANY) return true;
    if (text.startsWith(MAP_PREFIX) && text.endsWith(SHAPE_SUFFIX))
      return check(text.slice(MAP_PREFIX.length, -1));
    if (text.startsWith(LIST_PREFIX) && text.endsWith(SHAPE_SUFFIX))
      return check(text.slice(LIST_PREFIX.length, -1));
    return Object.prototype.hasOwnProperty.call(KNOWN_KEYS.types, text);
  };
  if (!check(KNOWN_KEYS.root)) bad.push(KNOWN_KEYS.root);
  for (const [typeName, keys] of Object.entries(KNOWN_KEYS.types)) {
    for (const [key, text] of Object.entries(keys)) {
      if (!check(text)) bad.push(`${typeName}.${key}: ${text}`);
    }
  }
  return bad;
}
